config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  resources :users do
    resources :reservations, only: [:index, :new, :edit]
    resources :workouts, only: [:show, :index, :new, :edit]
  end

  resources :workouts
  resources :reservations

  get '/auth/google_oauth2/callback', to: "sessions#google_login"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :workout
    belongs_to :user

    scope :past_reservations, ->(user_id) {joins(:workout).where(user_id: user_id).where("workouts.date < ?", DateTime.now)}
    scope :future_reservations, ->(user_id) {joins(:workout).where(user_id: user_id).where("workouts.date > ?", DateTime.now)}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :reservations
    has_many :workouts, through: :reservations

    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true

    def name
        "#{self.first_name} #{self.last_name}"
    end

    def past_workouts
        self.workouts.select {|w| w.date.to_date.past?}
    end

    def future_workouts
        self.workouts.select {|w| w.date.to_date.future?}
    end
end

app/models/workout.rb
class Workout < ApplicationRecord
    has_many :reservations
    has_many :users, through: :reservations
    validates :content, presence: true
    validates :date, presence: true
    validates :title, presence: true

    def format_date_time
        self.date.strftime("%B %e, %Y %l:%M %p")
    end

    def format_date
        self.date.strftime("%B %e, %Y")
    end

    def format_time
        self.date.strftime("%l:%M %p")
    end

    def format_name
        "#{self.format_date_time} - '#{self.title}'"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    def index
        @user = User.find_by_id(params[:user_id])
        @reservations = Reservation.past_reservations(@user.id)
    end
    
    def new
        if params[:user_id] && !User.exists?(params[:user_id])
            redirect_to "/", alert: "User not found."
          else
            @reservation = Reservation.new(user_id: params[:user_id])
            @workouts = Workout.all.select {|w| w.date.to_date.future?}
        end
    end

    def create
        # byebug
        @reservation = Reservation.new(reservation_params)
        if @reservation.save
            flash[:alert] = "Reservation successfully created!"
            redirect_to user_path(@reservation.user)
        else
            flash[:alert] = "An error occurred. Please try again."
            render :new
        end
    end
 
    def edit
        if params[:user_id]
            user = User.find_by_id(params[:user_id])
            if user.nil?
                redirect_to "/", alert: "User not found."
            else
                @reservation = user.reservations.find_by_id(params[:id])
                @workouts = Workout.all
                redirect_to to user_reservations_path(user), alert: "Reservation not found." if @reservation.nil?
            end
        else
            redirect_to "/", alert: "User not found."
        end
    end

    def update
        @reservation = Reservation.find_by_id(params[:id])
        @reservation.update(reservation_params)

        if @reservation.save
            flash[:alert] = "Reservation successfully updated!"
            redirect_to user_reservations_path(@reservation.user)
        else
            flash[:alert] = "An error occurred. Please try again."
            render :edit
        end
    end

    def destroy
        reservation = Reservation.find_by_id(params[:id])
        user = reservation.user
        reservation.destroy
        redirect_to user_path(user)
    end

    private

    def reservation_params
        params.require(:reservation).permit(:score, :user_id, :workout_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(email: params[:user][:email])
        if user
            if user.authenticate(params[:user][:password])
                flash[:alert] = "Success!"
                session[:user_id] = user.id
                redirect_to user_path(user)
            else
                flash[:alert] = "Incorrect password. Please try again."
                render :new
            end
        else
            flash[:alert] = "We could not find your account. Please check your information, or create an account."
            redirect_to '/'
        end
    end

    def destroy
        session.delete :user_id
        redirect_to '/'
    end

    def google_login
        user_email = request.env['omniauth.auth']['info']['email']
        user_first_name = request.env['omniauth.auth']['info']['first_name']
        user_last_name = request.env['omniauth.auth']['info']['last_name']

        @user = User.find_or_create_by(email: user_email) do |user|
            user.first_name = user_first_name
            user.last_name = user_last_name
            user.password = SecureRandom.hex
        end

        session[:user_id] = @user.id
        redirect_to user_path(@user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :login_check, except: [:index, :new, :create]
    before_action :current_user, except: [:index, :new, :create]

    def index
        @users = User.all
    end

    def show
        @reservations = Reservation.future_reservations(@user.id) #order this by date, sooner to later
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "User successfully created!"
            redirect_to user_path(@user)
        else
            flash[:alert] = "There was an error signing you up. Please try again."
            flash[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def update
        if @user.update(user_params)
            flash[:success] = "User successfully updated!"
            redirect_to user_path(@user)
        else
            flash[:alert] = "There was an error updating your profile. Please try again."
            render :edit
        end
    end

    def destroy
        flash[:success] = "Account deleted."
        session.delete :user_id
        @user.destroy
        redirect_to '/'
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def current_user
        @user = User.find_by_id(session[:user_id])
    end

    def login_check
        redirect_to '/' unless session[:user_id]
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :current_workout, except: [:index, :new, :create]

    def index
        @workouts = Workout.all
    end
    
    def new
        @workout = Workout.new
    end

    def create
        workout = Workout.new(workout_params)
        if workout.save
            flash[:alert] = "Workout successfully created!"
            workout.users << User.find_by_id(session[:user_id])
            redirect_to workout_path(workout)
        else
            flash[:alert] = "There was an error creating the workout. Please try again."
            render :new
        end
    end

    def update
        if @workout.update(workout_params)
            flash[:alert] = "Workout successfully updated!"
            redirect_to workout_path(@workout)
        else
            flash[:alert] = "There was an error editing the workout. Please try again."
            render :edit
        end
    end

    def destroy
        @workout.destroy
        redirect_to workouts_path
    end

    private

    def workout_params
        params.require(:workout).permit(:title, :content, :date, :user_id)
    end

    def current_workout
        @workout = Workout.find_by_id(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWorkoutApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:alert] %>
    <%= flash[:alert] %>
    <% flash[:errors]&.each do |e| %>
    <p><%= e %></p>
    <% end %>
  <% elsif flash[:success] %>
    <%= flash[:success] %>
  <% end %>   <!-- fix this -->
 

    <%= yield %>
    
    <% if User.find_by_id(session[:user_id]) %>
      <% @user = User.find_by_id(session[:user_id]) %>
      <br><br><%= link_to "Return to Home Page", user_path(@user) %><br>
      <%= button_to "Log Out", logout_path %>
    <% end %>
  </body>
</html>

app/views/reservations/edit.html.erb
<h2>Edit Your Reservation</h2>

<%= form_for(@reservation) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.text_area :score %>
    <%= f.collection_select :workout_id, @workouts, :id, :format_date_time %>
    <%= f.submit %>
<% end %>

app/views/reservations/index.html.erb
<h2>Your Workout History</h2>

<ul>
<% @reservations.each do |r| %>
    <li>
    <%= link_to r.workout.format_name, user_workout_path(r.user, r.workout) %>
        <ul>
        <li>
        <%= r.score || link_to("Add a Score!", edit_user_reservation_path(@user, r)) %>
        </li>
        </ul>
    </li>
    <br>
<% end %>
</ul>

app/views/reservations/new.html.erb
<h2>Make a Reservation</h2>

<%= form_for(@reservation) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.collection_select :workout_id, @workouts, :id, :format_date_time %>
    <%= f.submit %>
<% end %>

app/views/users/_users_form.html.erb
<%= form_for(@user) do |f| %>
    First Name: <%= f.text_field :first_name %><br>
    Last Name: <%= f.text_field :last_name %><br>
    Email: <%= f.text_field :email %><br>
    Password: <%= f.password_field :password %><br>
    Password Confirmation: <%= f.password_field :password_confirmation %><br>
    <%= f.submit "Submit" %>
  <% end %>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>

<%= render 'users_form' %>


<%= link_to 'Delete Profile', @user, method: :delete, data: { confirm: 'Are you sure you want to delete your profile?' } %>

app/views/users/index.html.erb
<h1>Our Members</h1><br><br>

<ul>
<% @users.each do |u| %>
    <li>
    <%= u.name %>
        <ul>
        <li>
        Workouts Completed: <%= Reservation.past_reservations(u.id).count %>
        </li>
    </li><br><br>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render 'users_form' %>

app/views/users/show.html.erb
<% if @user.first_name %>
    <h1>Welcome, <%= @user.first_name %>.</h1>
<% else %>
    <h1>Welcome.</h1>
<% end %>

<h3>Your Upcoming Workouts</h3>
<ul>
<% @reservations.each do |r| %>
    <li>
    <%= link_to r.workout.title, user_workout_path(@user, r.workout) %> - <%= r.workout.format_date %><br>
    <%= link_to "Change Reservation", edit_user_reservation_path(r.user, r) %><br>
    <%= link_to 'Cancel Reservation', r, method: :delete, data: { confirm: 'Cancel your reservation?' } %><br><br>
    </li>
<% end %>
</ul>
<br><br>
<%= link_to "All Workouts", workouts_path %><br>
<%= link_to "Post a Workout", new_user_workout_path(@user) %><br>
<%= link_to "Workout History", user_reservations_path(@user) %><br>
<%= link_to "Reserve a Workout", new_user_reservation_path(@user) %><br>
<%= link_to "Edit Profile", edit_user_path(@user) %>

app/views/users/welcome.html.erb
<h1>Welcome to CFG.</h1>

<%= link_to "Log In", login_path %><br>
<%= link_to "Sign Up", new_user_path %><br>
<%= link_to "Sign Up with Google", '/auth/google_oauth2' %>

app/views/workouts/_workouts_form.html.erb
<%= form_for(@workout) do |f| %>
    Title: <%= f.text_field :title %><br>
    Content: <%= f.text_area :content %><br>
    <%= f.datetime_select :date %>
    <%= f.submit "Submit" %>
  <% end %>

app/views/workouts/edit.html.erb
<h2>Edit Workout</h2>

<%= render 'workouts_form' %>

<%= link_to 'Delete Workout', @workout, method: :delete, data: { confirm: 'Delete this workout?' } %>

app/views/workouts/index.html.erb
<h1>All Available Classes</h1>

<!-- list of all workouts and class times, with links to sign up for a class or post a workout -->
<ul>
<% @workouts.each do |w| %>
    <li>
    <%= link_to w.format_name, workout_path(w) %>
        <ul>
        <li><%= link_to "Reserve This Workout", reservations_path(:reservation => {:user_id => session[:user_id], :workout_id => w.id}), method: "post" %>
        </li>
        </ul>
    </li><br><br>
<% end %>
</ul>

app/views/workouts/new.html.erb
<h1>Post a Workout</h1>

<%= render 'workouts_form' %>

app/views/workouts/show.html.erb
<h2>Workout - <%= @workout.format_date_time %></h2>

<h3><%= @workout.title %></h3>
<p><%= @workout.content %></p>

<ul>
<% @workout.users.each do |u| %>
    <li><%= u.name %></li><br>
<% end %>
</ul>

<%= link_to "Edit Workout", edit_workout_path(@workout) %>